//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ProjetoClinica.XPO.Database
{

    [Persistent(@"Appointments")]
    public partial class Appointmentsxpo : XPLiteObject
    {
        int fUniqueID;
        [Key(true)]
        public int UniqueID
        {
            get { return fUniqueID; }
            set { SetPropertyValue<int>(nameof(UniqueID), ref fUniqueID, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>(nameof(Type), ref fType, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value); }
        }
        DateTime fQueryStartDate;
        public DateTime QueryStartDate
        {
            get { return fQueryStartDate; }
            set { SetPropertyValue<DateTime>(nameof(QueryStartDate), ref fQueryStartDate, value); }
        }
        DateTime fQueryEndDate;
        public DateTime QueryEndDate
        {
            get { return fQueryEndDate; }
            set { SetPropertyValue<DateTime>(nameof(QueryEndDate), ref fQueryEndDate, value); }
        }
        bool fAllDay;
        public bool AllDay
        {
            get { return fAllDay; }
            set { SetPropertyValue<bool>(nameof(AllDay), ref fAllDay, value); }
        }
        string fSubject;
        [Size(50)]
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        string fLocation;
        [Size(50)]
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        int fLabel;
        public int Label
        {
            get { return fLabel; }
            set { SetPropertyValue<int>(nameof(Label), ref fLabel, value); }
        }
        int fResourceID;
        public int ResourceID
        {
            get { return fResourceID; }
            set { SetPropertyValue<int>(nameof(ResourceID), ref fResourceID, value); }
        }
        string fResourceIDs;
        [Size(SizeAttribute.Unlimited)]
        public string ResourceIDs
        {
            get { return fResourceIDs; }
            set { SetPropertyValue<string>(nameof(ResourceIDs), ref fResourceIDs, value); }
        }
        string fReminderInfo;
        [Size(SizeAttribute.Unlimited)]
        public string ReminderInfo
        {
            get { return fReminderInfo; }
            set { SetPropertyValue<string>(nameof(ReminderInfo), ref fReminderInfo, value); }
        }
        string fRecurrenceInfo;
        [Size(SizeAttribute.Unlimited)]
        public string RecurrenceInfo
        {
            get { return fRecurrenceInfo; }
            set { SetPropertyValue<string>(nameof(RecurrenceInfo), ref fRecurrenceInfo, value); }
        }
        string fTimeZoneId;
        [Size(SizeAttribute.Unlimited)]
        public string TimeZoneId
        {
            get { return fTimeZoneId; }
            set { SetPropertyValue<string>(nameof(TimeZoneId), ref fTimeZoneId, value); }
        }
        string fIdCliente;
        [Size(SizeAttribute.Unlimited)]
        public string IdCliente
        {
            get { return fIdCliente; }
            set { SetPropertyValue<string>(nameof(IdCliente), ref fIdCliente, value); }
        }
        string fIdMedico;
        [Size(SizeAttribute.Unlimited)]
        public string IdMedico
        {
            get { return fIdMedico; }
            set { SetPropertyValue<string>(nameof(IdMedico), ref fIdMedico, value); }
        }
    }

}
