//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ProjetoClinica.XPO.Database
{

    [Persistent(@"Resources")]
    public partial class Resourcesxpo : XPLiteObject
    {
        int fUniqueID;
        [Key(true)]
        public int UniqueID
        {
            get { return fUniqueID; }
            set { SetPropertyValue<int>(nameof(UniqueID), ref fUniqueID, value); }
        }
        int fResourceID;
        public int ResourceID
        {
            get { return fResourceID; }
            set { SetPropertyValue<int>(nameof(ResourceID), ref fResourceID, value); }
        }
        string fResourceName;
        [Size(50)]
        public string ResourceName
        {
            get { return fResourceName; }
            set { SetPropertyValue<string>(nameof(ResourceName), ref fResourceName, value); }
        }
        int fColor;
        public int Color
        {
            get { return fColor; }
            set { SetPropertyValue<int>(nameof(Color), ref fColor, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        tb_funcionariosxpo ffk_FunID;
        [Association(@"ResourcesxpoReferencestb_funcionariosxpo")]
        public tb_funcionariosxpo fk_FunID
        {
            get { return ffk_FunID; }
            set { SetPropertyValue<tb_funcionariosxpo>(nameof(fk_FunID), ref ffk_FunID, value); }
        }
    }

}
