//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ProjetoClinica.XPO.Database
{

    [Persistent(@"tb_cliente")]
    public partial class tb_clientexpo : XPLiteObject
    {
        int fcl_id;
        [Key(true)]
        public int cl_id
        {
            get { return fcl_id; }
            set { SetPropertyValue<int>(nameof(cl_id), ref fcl_id, value); }
        }
        string fcl_nome;
        public string cl_nome
        {
            get { return fcl_nome; }
            set { SetPropertyValue<string>(nameof(cl_nome), ref fcl_nome, value); }
        }
        string fcl_cpf;
        [Size(14)]
        public string cl_cpf
        {
            get { return fcl_cpf; }
            set { SetPropertyValue<string>(nameof(cl_cpf), ref fcl_cpf, value); }
        }
        string fcl_data_nascimento;
        [Size(11)]
        public string cl_data_nascimento
        {
            get { return fcl_data_nascimento; }
            set { SetPropertyValue<string>(nameof(cl_data_nascimento), ref fcl_data_nascimento, value); }
        }
        string fcl_telefone;
        [Size(16)]
        public string cl_telefone
        {
            get { return fcl_telefone; }
            set { SetPropertyValue<string>(nameof(cl_telefone), ref fcl_telefone, value); }
        }
        string fcl_email;
        public string cl_email
        {
            get { return fcl_email; }
            set { SetPropertyValue<string>(nameof(cl_email), ref fcl_email, value); }
        }
        string fcl_plano;
        [Size(50)]
        public string cl_plano
        {
            get { return fcl_plano; }
            set { SetPropertyValue<string>(nameof(cl_plano), ref fcl_plano, value); }
        }
        decimal fcl_altura;
        public decimal cl_altura
        {
            get { return fcl_altura; }
            set { SetPropertyValue<decimal>(nameof(cl_altura), ref fcl_altura, value); }
        }
        int fcl_peso;
        public int cl_peso
        {
            get { return fcl_peso; }
            set { SetPropertyValue<int>(nameof(cl_peso), ref fcl_peso, value); }
        }
        string fcl_tipo_sangue;
        [Size(4)]
        public string cl_tipo_sangue
        {
            get { return fcl_tipo_sangue; }
            set { SetPropertyValue<string>(nameof(cl_tipo_sangue), ref fcl_tipo_sangue, value); }
        }
        byte[] fcl_foto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] cl_foto
        {
            get { return fcl_foto; }
            set { SetPropertyValue<byte[]>(nameof(cl_foto), ref fcl_foto, value); }
        }
    }

}
