//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ProjetoClinica.XPO.Database
{

    [Persistent(@"tb_funcionarios")]
    public partial class tb_funcionariosxpo : XPLiteObject
    {
        int ffun_ID;
        [Key(true)]
        public int fun_ID
        {
            get { return ffun_ID; }
            set { SetPropertyValue<int>(nameof(fun_ID), ref ffun_ID, value); }
        }
        string ffun_Nome;
        [Size(50)]
        public string fun_Nome
        {
            get { return ffun_Nome; }
            set { SetPropertyValue<string>(nameof(fun_Nome), ref ffun_Nome, value); }
        }
        string ffun_DataNascimento;
        [Size(11)]
        public string fun_DataNascimento
        {
            get { return ffun_DataNascimento; }
            set { SetPropertyValue<string>(nameof(fun_DataNascimento), ref ffun_DataNascimento, value); }
        }
        string ffun_Email;
        public string fun_Email
        {
            get { return ffun_Email; }
            set { SetPropertyValue<string>(nameof(fun_Email), ref ffun_Email, value); }
        }
        string ffun_Telefone;
        [Size(16)]
        public string fun_Telefone
        {
            get { return ffun_Telefone; }
            set { SetPropertyValue<string>(nameof(fun_Telefone), ref ffun_Telefone, value); }
        }
        string ffun_CPF;
        [Size(15)]
        public string fun_CPF
        {
            get { return ffun_CPF; }
            set { SetPropertyValue<string>(nameof(fun_CPF), ref ffun_CPF, value); }
        }
        string ffun_CargoPrimario;
        [Size(50)]
        public string fun_CargoPrimario
        {
            get { return ffun_CargoPrimario; }
            set { SetPropertyValue<string>(nameof(fun_CargoPrimario), ref ffun_CargoPrimario, value); }
        }
        decimal ffun_Salario;
        public decimal fun_Salario
        {
            get { return ffun_Salario; }
            set { SetPropertyValue<decimal>(nameof(fun_Salario), ref ffun_Salario, value); }
        }
        string ffun_CargoFuncao;
        [Size(50)]
        public string fun_CargoFuncao
        {
            get { return ffun_CargoFuncao; }
            set { SetPropertyValue<string>(nameof(fun_CargoFuncao), ref ffun_CargoFuncao, value); }
        }
        string ffun_MedCRM;
        [Size(10)]
        public string fun_MedCRM
        {
            get { return ffun_MedCRM; }
            set { SetPropertyValue<string>(nameof(fun_MedCRM), ref ffun_MedCRM, value); }
        }
        byte[] ffun_foto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] fun_foto
        {
            get { return ffun_foto; }
            set { SetPropertyValue<byte[]>(nameof(fun_foto), ref ffun_foto, value); }
        }
        bool ffun_admin;
        public bool fun_admin
        {
            get { return ffun_admin; }
            set { SetPropertyValue<bool>(nameof(fun_admin), ref ffun_admin, value); }
        }
        string ffun_login;
        [Size(50)]
        public string fun_login
        {
            get { return ffun_login; }
            set { SetPropertyValue<string>(nameof(fun_login), ref ffun_login, value); }
        }
        string ffun_senha;
        [Size(50)]
        public string fun_senha
        {
            get { return ffun_senha; }
            set { SetPropertyValue<string>(nameof(fun_senha), ref ffun_senha, value); }
        }
        [Association(@"ResourcesxpoReferencestb_funcionariosxpo")]
        public XPCollection<Resourcesxpo> ResourcesxpoCollection { get { return GetCollection<Resourcesxpo>(nameof(ResourcesxpoCollection)); } }
    }

}
