// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ProjetoClinica.Models;

namespace ProjetoClinica.Context
{
    public partial class projeto_clinicaContext : DbContext
    {
        public projeto_clinicaContext()
        {
        }

        public projeto_clinicaContext(DbContextOptions<projeto_clinicaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_funcionarios> tb_funcionarios { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-UC3Q8T3\\SQLEXPRESS;Initial Catalog=projeto_clinicahospitalar;Persist Security Info=True;User ID=sa;Password=123;Encrypt=True; TrustServerCertificate=True");
            }
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}