// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetoClinica.Models
{
    public partial class Resources
    {
        [Key]
        public int UniqueID { get; set; }
        public int ResourceID { get; set; }
        [StringLength(50)]
        public string ResourceName { get; set; }
        public int? Color { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }
        public int? fk_FunID { get; set; }

        [ForeignKey("fk_FunID")]
        [InverseProperty("Resources")]
        public virtual tb_funcionarios fk_Fun { get; set; }
    }
}