// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetoClinica.Models
{
    public partial class tb_consultas
    {
        [Key]
        public int cslt_id { get; set; }
        public int cslt_fk_idcliente { get; set; }
        public int cslt_fk_idmedico { get; set; }
        public DateTime cslt_data_pedido { get; set; }
        public DateTime cslt_datamarcada { get; set; }

        [ForeignKey("cslt_fk_idcliente")]
        [InverseProperty("tb_consultas")]
        public virtual tb_cliente cslt_fk_idclienteNavigation { get; set; }
        [ForeignKey("cslt_fk_idmedico")]
        [InverseProperty("tb_consultas")]
        public virtual tb_funcionarios cslt_fk_idmedicoNavigation { get; set; }
    }
}